services:
    db:
        image: postgres:17.0
        hostname: ${DB_HOST}
        ports:
            - "5432:${DB_PORT}"
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        volumes:
            - pgdata:/var/lib/postgresql/data
            - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
        restart: unless-stopped
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
            interval: 10s
            timeout: 5s
            retries: 5
volumes:
    pgdata:
